name: hooks_state_notifier
description: Flutter hooks for StateNotifier.
version: 1.0.0
repository: https://github.com/TarekkMA/hooks_state_notifier

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  state_notifier: ^0.7.1
  flutter_hooks: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
